const OtherData = [
  {
    label: 'George Washington',
    type: 'President',
    presidency: 1,
    index: 1,
    term: [1, 2],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Portrait_of_George_Washington.jpeg/100px-Portrait_of_George_Washington.jpeg',
    url: '//en.wikipedia.org/wiki/George_Washington',
    party: 'No Party',
    birth: '1732-02-22',
    death: '1799-12-14',
    birthPlace: 'Westmoreland County, Virginia, USA',
    deathPlace: 'Mount Vernon, Virginia',
    religion: ['Anglican', 'Episcopal', 'Deist'],
    isClicked: false,
  },
  {
    label: 'John Adams',
    type: 'President',
    presidency: 2,
    index: 2,
    term: [3],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Gilbert_Stuart_John_Adams.jpg/101px-Gilbert_Stuart_John_Adams.jpg',
    url: '//en.wikipedia.org/wiki/John_Adams',
    party: 'Federalist',
    birth: '1735-10-30',
    death: '1826-07-04',
    birthPlace: 'Braintree, Massachusetts, USA',
    deathPlace: 'Quincy, Massachusetts',
    religion: ['Unitarian'],
    isClicked: false,
  },
  {
    label: 'Thomas Jefferson',
    type: 'President',
    presidency: 3,
    index: 3,
    term: [4, 5],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/4/46/T_Jefferson_by_Charles_Willson_Peale_1791_2.jpg/85px-T_Jefferson_by_Charles_Willson_Peale_1791_2.jpg',
    url: '//en.wikipedia.org/wiki/Thomas_Jefferson',
    party: 'Democratic-Republican',
    birth: '1743-04-13',
    death: '1826-07-04',
    birthPlace: 'Albemarle County, Virginia, USA',
    deathPlace: 'Charlottesville, Virginia',
    religion: ['Deism', 'quasi Unitarianism'],
    isClicked: false,
  },
  {
    label: 'James Madison',
    type: 'President',
    presidency: 4,
    index: 4,
    term: [6, 7],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/1/1d/James_Madison.jpg/88px-James_Madison.jpg',
    url: '//en.wikipedia.org/wiki/James_Madison',
    party: 'Democratic-Republican',
    birth: '1751-03-16',
    death: '1836-06-28',
    birthPlace: 'Port Conway, Virginia, USA',
    deathPlace: 'Montpelier, Virginia',
    religion: ['no affiliation'],
    isClicked: false,
  },
  {
    label: 'James Monroe',
    type: 'President',
    presidency: 5,
    index: 5,
    term: [8, 9],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Jamesmonroe-npgallery.jpg/100px-Jamesmonroe-npgallery.jpg',
    url: '//en.wikipedia.org/wiki/James_Monroe',
    party: 'Democratic-Republican',
    birth: '1758-04-28',
    death: '1831-07-04',
    birthPlace: 'Westmoreland County, Virginia, USA',
    deathPlace: 'New York City, New York',
    religion: ['no affiliation'],
    isClicked: false,
  },
  {
    label: 'John Quincy Adams',
    type: 'President',
    presidency: 6,
    index: 6,
    term: [10],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/6/64/John_Quincy_Adams.jpg/100px-John_Quincy_Adams.jpg',
    url: '//en.wikipedia.org/wiki/John_Quincy_Adams',
    party: 'Democratic-Republican',
    birth: '1767-07-11',
    death: '1848-02-23',
    birthPlace: 'Braintree, Massachusetts, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['Unitarian'],
    isClicked: false,
  },
  {
    label: 'Andrew Jackson',
    type: 'President',
    presidency: 7,
    index: 7,
    term: [11, 12],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/6/64/Andrew_Jackson.jpg/99px-Andrew_Jackson.jpg',
    url: '//en.wikipedia.org/wiki/Andrew_Jackson',
    party: 'Democratic',
    birth: '1767-03-15',
    death: '1845-06-08',
    birthPlace: 'Waxhaws area, South Carolina, USA',
    deathPlace: 'Nashville, Tennessee',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'Martin Van Buren',
    type: 'President',
    presidency: 8,
    index: 8,
    term: [13],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Martin_Van_Buren.jpg/100px-Martin_Van_Buren.jpg',
    url: '//en.wikipedia.org/wiki/Martin_Van_Buren',
    party: 'Democratic',
    birth: '1782-12-05',
    death: '1862-07-24',
    birthPlace: 'Kinderhook, New York, USA',
    deathPlace: 'Kinderhook, New York',
    religion: ['Dutch Reformed'],
    isClicked: false,
  },
  {
    label: 'William Harrison',
    type: 'President',
    presidency: 9,
    index: 9,
    term: [14],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/e/ea/William_Henry_Harrison.jpg/90px-William_Henry_Harrison.jpg',
    url: '//en.wikipedia.org/wiki/William_Henry_Harrison',
    party: 'Whig',
    birth: '1773-02-09',
    death: '1841-04-04',
    birthPlace: 'Charles City County, Virginia, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'John Tyler',
    type: 'President',
    presidency: 10,
    index: 10,
    term: [14],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/c/c5/John_Tyler.jpg/100px-John_Tyler.jpg',
    url: '//en.wikipedia.org/wiki/John_Tyler',
    party: 'Whig',
    birth: '1790-03-29',
    death: '1862-01-18',
    birthPlace: 'Charles City County, Virginia, USA',
    deathPlace: 'Richmond, Virginia',
    religion: ['The Episcopal Church', 'Deism'],
    isClicked: false,
  },
  {
    label: 'James Polk',
    type: 'President',
    presidency: 11,
    index: 11,
    term: [15],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/b/be/Polkpolk.jpg/90px-Polkpolk.jpg',
    url: '//en.wikipedia.org/wiki/James_K._Polk',
    party: 'Democratic',
    birth: '1795-11-02',
    death: '1849-06-15',
    birthPlace: 'Mecklenburg County, North Carolina, USA',
    deathPlace: 'Nashville, Tennessee',
    religion: ['Presbyterian', 'Methodist'],
    isClicked: false,
  },
  {
    label: 'Zachary Taylor',
    type: 'President',
    presidency: 12,
    index: 12,
    term: [16],
    dieInOffice: 'yes',
    imageURL:
      'https://i2.wp.com/www.nationalreview.com/wp-content/uploads/2016/06/zachary-taylor-donald-trump-republican-party-r-2.jpg?resize=300%2C300&ssl=1',
    url: '//en.wikipedia.org/wiki/Zachary_Taylor',
    party: 'Whig',
    birth: '1784-11-24',
    death: '1850-07-09',
    birthPlace: 'Barboursville, Virginia, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'Millard Fillmore',
    type: 'President',
    presidency: 13,
    index: 13,
    term: [16],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Millard_Fillmore.jpg/100px-Millard_Fillmore.jpg',
    url: '//en.wikipedia.org/wiki/Millard_Fillmore',
    party: 'Whig',
    birth: '1800-01-07',
    death: '1874-03-08',
    birthPlace: 'Summerhill, New York, USA',
    deathPlace: 'Buffalo, New York',
    religion: ['Unitarian'],
    isClicked: false,
  },
  {
    label: 'Franklin Pierce',
    type: 'President',
    presidency: 14,
    index: 14,
    term: [17],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Franklin_Pierce.jpg/100px-Franklin_Pierce.jpg',
    url: '//en.wikipedia.org/wiki/Franklin_Pierce',
    party: 'Democratic',
    birth: '1804-11-23',
    death: '1869-10-08',
    birthPlace: 'Hillsborough, New Hampshire, USA',
    deathPlace: 'Concord, New Hampshire',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'James Buchanan',
    type: 'President',
    presidency: 15,
    index: 15,
    term: [18],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/f/fd/James_Buchanan.jpg/100px-James_Buchanan.jpg',
    url: '//en.wikipedia.org/wiki/James_Buchanan',
    party: 'Democratic',
    birth: '1791-04-23',
    death: '1868-06-01',
    birthPlace: 'Cove Gap, Pennsylvania, USA',
    deathPlace: 'Lancaster, Pennsylvania',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'Abraham Lincoln',
    type: 'President',
    presidency: 16,
    index: 16,
    term: [19, 20],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/4/44/Abraham_Lincoln_head_on_shoulders_photo_portrait.jpg/100px-Abraham_Lincoln_head_on_shoulders_photo_portrait.jpg',
    url: '//en.wikipedia.org/wiki/Abraham_Lincoln',
    party: 'Republican',
    birth: '1809-02-12',
    death: '1865-04-15',
    birthPlace: 'Hardin County, Kentucky, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['no affiliation'],
    isClicked: false,
  },
  {
    label: 'Andrew Johnson',
    type: 'President',
    presidency: 17,
    index: 17,
    term: [20],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Andrew_johnson2.jpg/98px-Andrew_johnson2.jpg',
    url: '//en.wikipedia.org/wiki/Andrew_Johnson',
    party: 'Democratic',
    birth: '1808-12-29',
    death: '1875-07-31',
    birthPlace: 'Raleigh, North Carolina, USA',
    deathPlace: 'Greeneville, Tennessee',
    religion: ['no affiliation'],
    isClicked: false,
  },
  {
    label: 'Ulysses Grant',
    type: 'President',
    presidency: 18,
    index: 18,
    term: [21, 22],
    dieInOffice: 'no',
    imageURL:
      'https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTE5NTU2MzE2MjM2Nzc2OTcx/ulysses-s-grant-9318285-1-402.jpg',
    url: '//en.wikipedia.org/wiki/Ulysses_Grant',
    party: 'Republican',
    birth: '1822-04-27',
    death: '1885-07-23',
    birthPlace: 'Point Pleasant, Ohio, USA',
    deathPlace: 'Mount McGregor, New York',
    religion: ['never baptized'],
    isClicked: false,
  },
  {
    label: 'Rutherford Hayes',
    type: 'President',
    presidency: 19,
    index: 19,
    term: [23],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/9/97/President_Rutherford_Hayes_1870_-_1880.jpg/100px-President_Rutherford_Hayes_1870_-_1880.jpg',
    url: '//en.wikipedia.org/wiki/Rutherford_Hayes',
    party: 'Republican',
    birth: '1822-10-04',
    death: '1893-01-17',
    birthPlace: 'Delaware, Ohio, USA',
    deathPlace: 'Fremont, Ohio',
    religion: ['no affiliation'],
    isClicked: false,
  },
  {
    label: 'James Garfield',
    type: 'President',
    presidency: 20,
    index: 20,
    term: [24],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/1/1f/James_Abram_Garfield%2C_photo_portrait_seated.jpg/100px-James_Abram_Garfield%2C_photo_portrait_seated.jpg',
    url: '//en.wikipedia.org/wiki/James_Garfield',
    party: 'Republican',
    birth: '1831-11-19',
    death: '1881-09-19',
    birthPlace: 'Moreland Hills, Ohio, USA',
    deathPlace: 'Elberon (Long Branch), New Jersey',
    religion: ['Church of Christ'],
    isClicked: false,
  },
  {
    label: 'Chester Arthur',
    type: 'President',
    presidency: 21,
    index: 21,
    term: [24],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Chester_Alan_Arthur.jpg/100px-Chester_Alan_Arthur.jpg',
    url: '//en.wikipedia.org/wiki/Chester_Arthur',
    party: 'Republican',
    birth: '1830-10-05',
    death: '1886-11-18',
    birthPlace: 'Fairfield, Vermont, USA',
    deathPlace: 'New York City, New York',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'Grover Cleveland',
    type: 'President',
    presidency: [22, 24],
    index: 22,
    term: [25, 27],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/9/91/President_Grover_Cleveland.jpg/100px-President_Grover_Cleveland.jpg',
    url: '//en.wikipedia.org/wiki/Grover_Cleveland',
    party: 'Democratic',
    birth: '1837-03-18',
    death: '1908-06-24',
    birthPlace: 'Caldwell, New Jersey, USA',
    deathPlace: 'Princeton, New Jersey',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'Benjamin Harrison',
    type: 'President',
    presidency: 23,
    index: 23,
    term: [26],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg/100px-Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg',
    url: '//en.wikipedia.org/wiki/Benjamin_Harrison',
    party: 'Republican',
    birth: '1833-08-20',
    death: '1901-03-13',
    birthPlace: 'North Bend, Ohio, USA',
    deathPlace: 'Indianapolis, Indiana',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'William McKinley',
    type: 'President',
    presidency: 25,
    index: 24,
    term: [28, 29],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Mckinley.jpg/100px-Mckinley.jpg',
    url: '//en.wikipedia.org/wiki/William_McKinley',
    party: 'Republican',
    birth: '1843-01-29',
    death: '1901-09-14',
    birthPlace: 'Niles, Ohio, USA',
    deathPlace: 'Buffalo, New York',
    religion: ['Methodist'],
    isClicked: false,
  },
  {
    label: 'Theodore Roosevelt',
    type: 'President',
    presidency: 26,
    index: 25,
    term: [29, 30],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/1/19/President_Theodore_Roosevelt%2C_1904.jpg/100px-President_Theodore_Roosevelt%2C_1904.jpg',
    url: '//en.wikipedia.org/wiki/Theodore_Roosevelt',
    party: 'Republican',
    birth: '1858-10-27',
    death: '1919-01-06',
    birthPlace: 'New York City, New York, USA',
    deathPlace: 'Oyster Bay, New York',
    religion: ['Dutch Reformed'],
    isClicked: false,
  },
  {
    label: 'William Taft',
    type: 'President',
    presidency: 27,
    index: 26,
    term: [31],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/William_Howard_Taft%2C_Bain_bw_photo_portrait%2C_1908.jpg/100px-William_Howard_Taft%2C_Bain_bw_photo_portrait%2C_1908.jpg',
    url: '//en.wikipedia.org/wiki/William_Taft',
    party: 'Republican',
    birth: '1857-09-15',
    death: '1930-03-08',
    birthPlace: 'Cincinnati, Ohio, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['Unitarian'],
    isClicked: false,
  },
  {
    label: 'Woodrow Wilson',
    type: 'President',
    presidency: 28,
    index: 27,
    term: [32, 33],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/2/2d/President_Woodrow_Wilson_portrait_December_2_1912.jpg/100px-President_Woodrow_Wilson_portrait_December_2_1912.jpg',
    url: '//en.wikipedia.org/wiki/Woodrow_Wilson',
    party: 'Democratic',
    birth: '1856-12-28',
    death: '1924-02-03',
    birthPlace: 'Staunton, Virginia, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'Warren Harding',
    type: 'President',
    presidency: 29,
    index: 28,
    term: [34],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/8/87/Warren_G_Harding_portrait_as_senator_June_1920.jpg/100px-Warren_G_Harding_portrait_as_senator_June_1920.jpg',
    url: '//en.wikipedia.org/wiki/Warren_Harding',
    party: 'Republican',
    birth: '1865-11-02',
    death: '1923-08-02',
    birthPlace: 'Blooming Grove, Ohio, USA',
    deathPlace: 'San Francisco, California',
    religion: ['Baptist'],
    isClicked: false,
  },
  {
    label: 'Calvin Coolidge',
    type: 'President',
    presidency: 30,
    index: 29,
    term: [34, 35],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Calvin_Coolidge_photo_portrait_head_and_shoulders.jpg/100px-Calvin_Coolidge_photo_portrait_head_and_shoulders.jpg',
    url: '//en.wikipedia.org/wiki/Calvin_Coolidge',
    party: 'Republican',
    birth: '1872-07-04',
    death: '1933-01-05',
    birthPlace: 'Plymouth, Vermont, USA',
    deathPlace: 'Northampton, Massachusetts',
    religion: ['Congregationalist'],
    isClicked: false,
  },
  {
    label: 'Herbert Hoover',
    type: 'President',
    presidency: 31,
    index: 30,
    term: [36],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/HerbertHoover.jpg/100px-HerbertHoover.jpg',
    url: '//en.wikipedia.org/wiki/Herbert_Hoover',
    party: 'Republican',
    birth: '1874-08-10',
    death: '1964-10-20',
    birthPlace: 'West Branch, Iowa, USA',
    deathPlace: 'New York City, New York',
    religion: ['Quaker'],
    isClicked: false,
  },
  {
    label: 'Franklin D. Roosevelt',
    type: 'President',
    presidency: 32,
    index: 31,
    term: [37, 38, 39, 40],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/b/b8/FDR_in_1933.jpg/100px-FDR_in_1933.jpg',
    url: '//en.wikipedia.org/wiki/Franklin_D._Roosevelt',
    party: 'Democratic',
    birth: '1882-01-30',
    death: '1945-04-12',
    birthPlace: 'Hyde Park, New York, USA',
    deathPlace: 'Warm Springs, Georgia',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'Harry Truman',
    type: 'President',
    presidency: 33,
    index: 32,
    term: [40, 41],
    dieInOffice: 'no',
    imageURL: 'https://www.famousbirthdays.com/faces/truman-harry-image.jpg',
    url: '//en.wikipedia.org/wiki/Harry_Truman',
    party: 'Democratic',
    birth: '1884-05-08',
    death: '1972-12-26',
    birthPlace: 'Lamar, Missouri, USA',
    deathPlace: 'Kansas City, Missouri',
    religion: ['Baptist'],
    isClicked: false,
  },
  {
    label: 'Dwight Eisenhower',
    type: 'President',
    presidency: 34,
    index: 33,
    term: [42, 43],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Eisenhower_official.jpg/100px-Eisenhower_official.jpg',
    url: '//en.wikipedia.org/wiki/Dwight_Eisenhower',
    party: 'Republican',
    birth: '1890-10-14',
    death: '1969-03-28',
    birthPlace: 'Denison, Texas, USA',
    deathPlace: 'Washington, D.C.',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'John F. Kennedy',
    type: 'President',
    presidency: 35,
    index: 34,
    term: [44],
    dieInOffice: 'yes',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/3/3f/John_F_Kennedy.jpg/100px-John_F_Kennedy.jpg',
    url: '//en.wikipedia.org/wiki/John_F._Kennedy',
    party: 'Democratic',
    birth: '1917-05-29',
    death: '1963-11-22',
    birthPlace: 'Brookline, Massachusetts, USA',
    deathPlace: 'Dallas, Texas',
    religion: ['Roman Catholic'],
    isClicked: false,
  },
  {
    label: 'Lyndon Johnson',
    type: 'President',
    presidency: 36,
    index: 35,
    term: [44, 45],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Lbj2.jpg/100px-Lbj2.jpg',
    url: '//en.wikipedia.org/wiki/Lyndon_B._Johnson',
    party: 'Democratic',
    birth: '1908-08-27',
    death: '1973-01-22',
    birthPlace: 'Stonewall, Texas, USA',
    deathPlace: 'Stonewall, Texas',
    religion: ['Disciple of Christ'],
    isClicked: false,
  },
  {
    label: 'Richard Nixon',
    type: 'President',
    presidency: 37,
    index: 36,
    term: [46, 47],
    dieInOffice: 'no',
    imageURL:
      'https://si.wsj.net/public/resources/images/AR-AM660_NIXON_8S_20160406102704.jpg',
    url: '//en.wikipedia.org/wiki/Richard_Nixon',
    party: 'Republican',
    birth: '1913-01-09',
    death: '1994-04-22',
    birthPlace: 'Yorba Linda, California, USA',
    deathPlace: 'New York City, New York',
    religion: ['Quaker'],
    isClicked: false,
  },
  {
    label: 'Gerald Ford',
    type: 'President',
    presidency: 38,
    index: 37,
    term: [47],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Gerald_Ford.jpg/100px-Gerald_Ford.jpg',
    url: '//en.wikipedia.org/wiki/Gerald_Ford',
    party: 'Republican',
    birth: '1913-07-14',
    death: '2006-12-26',
    birthPlace: 'Omaha, Nebraska, USA',
    deathPlace: 'Rancho Mirage, California, USA',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'Jimmy Carter',
    type: 'President',
    presidency: 39,
    index: 38,
    term: [48],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Jimmy_Carter.jpg/100px-Jimmy_Carter.jpg',
    url: '//en.wikipedia.org/wiki/Jimmy_Carter',
    party: 'Democratic',
    birth: '1924-10-01',
    birthPlace: 'Plains, Georgia, USA',
    religion: ['Baptist'],
    isClicked: false,
  },
  {
    label: 'Ronald Reagan',
    type: 'President',
    presidency: 40,
    index: 39,
    term: [49, 50],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/1/16/Official_Portrait_of_President_Reagan_1981.jpg/100px-Official_Portrait_of_President_Reagan_1981.jpg',
    url: '//en.wikipedia.org/wiki/Ronald_Reagan',
    party: 'Republican',
    birth: '1911-02-06',
    death: '2004-06-05',
    birthPlace: 'Tampico, Illinois, USA',
    deathPlace: 'Bel-Air, California',
    religion: ['Presbyterian'],
    isClicked: false,
  },
  {
    label: 'George H.W. Bush',
    type: 'President',
    presidency: 41,
    index: 40,
    term: [51],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/0/0f/George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait.jpg/100px-George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait.jpg',
    url: '//en.wikipedia.org/wiki/George_H._W._Bush',
    party: 'Republican',
    birth: '1924-06-12',
    birthPlace: 'Milton, Massachusetts, USA',
    religion: ['Episcopal'],
    isClicked: false,
  },
  {
    label: 'Bill Clinton',
    type: 'President',
    presidency: 42,
    index: 41,
    term: [52, 53],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bill_Clinton.jpg/100px-Bill_Clinton.jpg',
    url: '//en.wikipedia.org/wiki/Bill_Clinton',
    party: 'Democratic',
    birth: '1946-08-19',
    birthPlace: 'Hope, Arkansas, USA',
    religion: ['Baptist'],
    isClicked: false,
  },
  {
    label: 'George W. Bush',
    type: 'President',
    presidency: 43,
    index: 42,
    term: [54, 55],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/George-W-Bush.jpeg/100px-George-W-Bush.jpeg',
    url: '//en.wikipedia.org/wiki/George_W._Bush',
    party: 'Republican',
    birth: '1946-07-06',
    birthPlace: 'New Haven, Connecticut, USA',
    religion: ['Methodist'],
    isClicked: false,
  },
  {
    label: 'Barack Obama',
    type: 'President',
    presidency: 44,
    index: 43,
    term: [56],
    dieInOffice: 'no',
    imageURL:
      '//upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Official_portrait_of_Barack_Obama.jpg/100px-Official_portrait_of_Barack_Obama.jpg',
    url: '//en.wikipedia.org/wiki/Barack_Obama',
    party: 'Democratic',
    birth: '1961-08-04',
    birthPlace: 'Honolulu, Hawaii, USA',
    religion: ['Christian'],
    isClicked: false,
  },
  {
    label: 'Donald J Trump',
    type: 'President',
    presidency: 45,
    index: 43,
    imageURL:
      'https://cdn.i-scmp.com/sites/default/files/styles/768x768/public/d8/images/methode/2019/07/16/7292a6b2-a73c-11e9-8d5c-2d5b58977904_image_hires_041405.jpg?itok=tbJ6jDRm&v=1563221650',
    party: 'Republican',

    isClicked: false,
  },
];

export default OtherData;
